### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by saxbophone** [saxbophone/unmoving#4]
- [x] Choose a software license _MPL-2.0_
  - [x] Add license declarations to the project
- [x] Add user-friendly basic usage instructions through use of code samples in README
- [x] Test importability of the project in CMake _Yes --you must remember to build your dependent project as C++20 though!_
- [x] Consider longevity of current public symbol names in the context of possible widening of this library's scope to a general-purpose fixed-point data type (should `Fixed` be renamed to `PSXFixed` or `PSXFixed16` in anticipation of a generic `Fixed` type taking its name?)
- [x] Add clear disclaimers about runtime efficiency testing on actual PSX platform
- [x] Test with C++ standards older than C++20 _c++17 works if double ctor is changed to call default ctor in initialiser. This works on all except MSVC_.
  - [x] document that code is developed on C++20 primarily.
  - [x] document the modified build process for PSn00bSDK to get a C++20-compatible toolchain (not much changed if you just want language with no language support headers, just have to use very recent binutils and gcc --document the versions of these I used, maybe also the process for getting a sort-of-working set of language support headers...)
- [x] Restructure project into true header-only-library
- [x] Add missing documentation
  - [x] Specify the parameters of the Fixed type using Q notation
- [x] Flatten namespace
- [x] Add instructions for including with CMake and that users can also just copy the header file
